### ISSUE TITLE
command form not completed

### ISSUE THREAD

**Issue by richard28530** [Mellanox/hw-mgmt#45]
I found these syslog in my switch
<pre>
    May 23 16:56:44.455254 sonic-215 ERR systemd-udevd[268]: invalid key/value pair in file /lib/udev/rules.d/50-mellanox-system-event.rules on line 242, starting at character 120 (',')
    May 23 16:56:44.455267 sonic-215 ERR systemd-udevd[268]: invalid key/value pair in file /lib/udev/rules.d/50-mellanox-system-event.rules on line 243, starting at character 120 (',')
    May 23 16:56:52.088542 sonic-215 ERR systemd-udevd[268]: invalid key/value pair in file /lib/udev/rules.d/50-mellanox-system-event.rules on line 242, starting at character 120 (',')
    May 23 16:56:52.090680 sonic-215 ERR systemd-udevd[268]: invalid key/value pair in file /lib/udev/rules.d/50-mellanox-system-event.rules on line 243, starting at character 120 (',')
    May 23 16:56:54.700694 sonic-215 ERR systemd-udevd[268]: invalid key/value pair in file /lib/udev/rules.d/50-mellanox-system-event.rules on line 242, starting at character 120 (',')
    May 23 16:56:54.701360 sonic-215 ERR systemd-udevd[268]: invalid key/value pair in file /lib/udev/rules.d/50-mellanox-system-event.rules on line 243, starting at character 120 (',')

</pre>

https://github.com/Mellanox/hw-mgmt/blob/498002ba528e5633bf1e9b8e488979ed731ca0f6/usr/lib/udev/rules.d/50-mellanox-system-event.rules#L242

line 242 243 RUN+=".....
i assume this should be enclose by an " 
<pre>
# Hotplug devices statuses
SUBSYSTEM=="hwmon", DEVPATH=="/devices/platform/mlxplat/mlxreg-hotplug/hwmon/hwmon*", ACTION=="add", RUN+="/usr/bin/mellanox-system-event.sh add hotplug %S %p"
SUBSYSTEM=="hwmon", DEVPATH=="/devices/platform/mlxplat/mlxreg-hotplug/hwmon/hwmon*", ACTION=="remove", RUN+="/usr/bin/mellanox-system-event.sh rm hotplug %S %p"
SUBSYSTEM=="hwmon", DEVPATH=="/devices/platform/mlxplat/mlxreg-hotplug/hwmon/hwmon*", ATTR{asic1}=="2" ACTION=="change", RUN+="/usr/bin/mellanox-thermal-events.sh change hotplug_asic up %S %p
SUBSYSTEM=="hwmon", DEVPATH=="/devices/platform/mlxplat/mlxreg-hotplug/hwmon/hwmon*", ATTR{asic1}=="0" ACTION=="change", RUN+="/usr/bin/mellanox-thermal-events.sh change hotplug_asic down %S %p

</pre>

**Comment by ozohad** [comment]
This has been fixed a few months back, please use a newer version or apply this change manually.
